/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const EnrollmentId = IDL.Nat;
export const EnrollmentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'reviewed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Enrollment = IDL.Record({
  'id' : EnrollmentId,
  'status' : EnrollmentStatus,
  'submittedAt' : Timestamp,
  'email' : IDL.Text,
  'childAge' : IDL.Text,
  'message' : IDL.Text,
  'programInterest' : IDL.Text,
  'phone' : IDL.Text,
  'childName' : IDL.Text,
  'parentName' : IDL.Text,
});
export const TestimonialId = IDL.Nat;
export const Testimonial = IDL.Record({
  'id' : TestimonialId,
  'quote' : IDL.Text,
  'rating' : IDL.Nat,
  'childProgram' : IDL.Text,
  'parentName' : IDL.Text,
});
export const EnrollmentRequest = IDL.Record({
  'email' : IDL.Text,
  'childAge' : IDL.Text,
  'message' : IDL.Text,
  'programInterest' : IDL.Text,
  'phone' : IDL.Text,
  'childName' : IDL.Text,
  'parentName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'getStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalEnrollments' : IDL.Nat,
          'totalTestimonials' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'listEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
  'listTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'markEnrollmentReviewed' : IDL.Func([EnrollmentId], [], []),
  'submitEnrollment' : IDL.Func([EnrollmentRequest], [EnrollmentId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const EnrollmentId = IDL.Nat;
  const EnrollmentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'reviewed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Enrollment = IDL.Record({
    'id' : EnrollmentId,
    'status' : EnrollmentStatus,
    'submittedAt' : Timestamp,
    'email' : IDL.Text,
    'childAge' : IDL.Text,
    'message' : IDL.Text,
    'programInterest' : IDL.Text,
    'phone' : IDL.Text,
    'childName' : IDL.Text,
    'parentName' : IDL.Text,
  });
  const TestimonialId = IDL.Nat;
  const Testimonial = IDL.Record({
    'id' : TestimonialId,
    'quote' : IDL.Text,
    'rating' : IDL.Nat,
    'childProgram' : IDL.Text,
    'parentName' : IDL.Text,
  });
  const EnrollmentRequest = IDL.Record({
    'email' : IDL.Text,
    'childAge' : IDL.Text,
    'message' : IDL.Text,
    'programInterest' : IDL.Text,
    'phone' : IDL.Text,
    'childName' : IDL.Text,
    'parentName' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'getStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalEnrollments' : IDL.Nat,
            'totalTestimonials' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'listEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
    'listTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'markEnrollmentReviewed' : IDL.Func([EnrollmentId], [], []),
    'submitEnrollment' : IDL.Func([EnrollmentRequest], [EnrollmentId], []),
  });
};

export const init = ({ IDL }) => { return []; };